apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: echo-server
spec:
  replicas: 1
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: mendhak/http-https-echo
        ports:
          - containerPort: 80
          - containerPort: 443
         
